=== ShikaTheRock/ASIR1-Workspace/WEBS/xsdFinaleComplex/complejo1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="cpCrrect">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="46000"/>
            <xs:maxInclusive value="46999"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="alumno">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="direccion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="calle" type="xs:string" />
                            <xs:element name="numero" type="xs:integer" />
                            <xs:element name="ciudad" type="xs:string" />
                            <xs:element name="cp" type="cpCrrect" />
                            <xs:element name="provincia" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="telefono" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="dni" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ShikaTheRock/ASIR1-Workspace/WEBS/xsdFinaleComplex/complejo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumno xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="complejo1.xsd" dni="11111111">
    <nombre>Lorenzo Pérez</nombre>
    <direccion>
        <calle>Banderas</calle>
        <numero>7</numero> 
        <ciudad>Alfafar</ciudad>
        <cp>46910</cp> 
        <provincia>Valencia</provincia>
    </direccion>
    <telefono>961555555</telefono>
</alumno>
