=== ShikaTheRock/ASIR1-Workspace/WEBS/XSD5/02_c.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inmobiliaria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="agencias">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="agencia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="email" type="xs:string" />
                                        <xs:element name="tlf" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="propietarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="propietario">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="inmuebles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inmueble">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="numpisos" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pisos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="piso" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="descripcion" type="xs:string" />
                                        <xs:element name="tipo" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ShikaTheRock/ASIR1-Workspace/WEBS/XSD5/02_c.xml
<?xml version="1.0" encoding="UTF-8"?>
<inmobiliaria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="02_c.xsd">
	
	<agencias>
        <agencia>
            <nombre>První realitní</nombre>
            <email>info@realitka.cz</email>
            <tlf>+420 481 234 567</tlf>
        </agencia>
	</agencias>
    
    <propietarios>
        <propietario>
            <nombre>Alexandr Kendík</nombre>
        </propietario>
	</propietarios>
    
    <inmuebles>
        <inmueble>
            <nombre>Krb</nombre>
            <numpisos>20</numpisos>
        </inmueble>
	</inmuebles>
    
    <pisos>
        <piso>
            <nombre>K0101</nombre>
            <descripcion>Small flat with no windows</descripcion>
            <tipo>1234</tipo>
        </piso>
        <piso>
            <nombre>K1501</nombre>
            <descripcion>Luxury flat with a huge terrace</descripcion>
            <tipo>12345</tipo>
        </piso>
	</pisos>
    
</inmobiliaria>
